"""<br>Copyright (C) 2024 Dean Zarkov<br>deanzarkov@protonmail.com<br><br>Created by Dean Zarkov<br><br>This file is part of "Stylized Hair PRO".<br>
<br> "Stylized Hair PRO" is free software; you can redistribute it and/or<br> modify it under the terms of the GNU General Public License<br>
as published by the Free Software Foundation; either version 3<br> of the License, or (at your option) any later version.<br><br>
This program is distributed in the hope that it will be useful,<br> but WITHOUT ANY WARRANTY; without even the implied warranty of<br>
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the<br> GNU General Public License for more details.<br><br>
You should have received a copy of the GNU General Public License<br> along with this program; if not, see <https://www.gnu.org<br>/licenses>.<br>"""

# shp_inp(smi[''])
# 'Control Option' - 'Modifier Socket' pairs
SHP_MODIFIER_INPUTS = {
    # MAIN
    'x_mirror'                              : 'Input_169', 
    'y_mirror'                              : 'Socket_79', 
    'z_mirror'                              : 'Socket_80', 
    'main_thickness'                        : 'Input_10', 
    'main_rotation'                         : 'Input_2', 
    # SHAPE
    'root_thickness'                        : 'Input_50', 
    'tip_thickness'                         : 'Input_47', 
    'thickness_factor'                      : 'Input_53', 
    'thickness_contrast'                    : 'Input_162', 
    'tip_open'                              : 'Input_49', 
    'tip_bulge'                             : 'Input_48', 
    'tip_roundness'                         : 'Input_51', 
    'root_open'                             : 'Input_52', 
    'flat_root'                             : 'Input_166', 
    'flat_tip'                              : 'Input_165', 
    'flatness_factor'                       : 'Input_163', 
    'flatness_contrast'                     : 'Input_164', 
    'flip_flatten_axis'                     : 'Input_167',
    'use_original_thickness'                : 'Socket_120', 
    # TWIST
    'twist_root'                            : 'Input_161', 
    'twist_mid'                             : 'Input_160', 
    'twist_tip'                             : 'Input_159', 
    'twist_1_amount'                        : 'Input_22', 
    'twist_1_position'                      : 'Input_20', 
    'twist_1_spread'                        : 'Input_21', 
    'twist_2_amount'                        : 'Input_24', 
    'twist_2_position'                      : 'Input_25', 
    'twist_2_spread'                        : 'Input_26', 
    'twist_3_amount'                        : 'Socket_2', 
    'twist_3_position'                      : 'Socket_1', 
    'twist_3_spread'                        : 'Socket_3', 
    'waviness'                              : 'Input_131', 
    'waviness_scale'                        : 'Input_132', 
    'waviness_seed'                         : 'Input_133', 
    # BUMPS
    'bumps_regular_strength'                : 'Input_55', 
    'bumps_regular_count'                   : 'Input_56', 
    'bumps_regular_shape'                   : 'Input_100', 
    'bumps_regular_gap_size'                : 'Input_134', 
    'bumps_random_strength'                 : 'Input_58', 
    'bumps_random_contrast'                 : 'Socket_6', 
    'bumps_random_scale'                    : 'Input_101', 
    'bumps_random_seed'                     : 'Input_102', 
    'bumps_surface_strength'                : 'Socket_7', 
    'bumps_surface_scale'                   : 'Socket_8', 
    'bumps_surface_seed'                    : 'Socket_9', 
    'bumps_factor'                          : 'Input_60', 
    'bumps_contrast'                        : 'Input_135', 
    # CURLS
    'curls_flip_dir'                        : 'Input_45', 
    'curls_frequency'                       : 'Input_41', 
    'curls_radius'                          : 'Input_42', 
    'curls_phase'                           : 'Input_78', 
    'curls_noise_amount'                    : 'Input_62', 
    'curls_noise_seed'                      : 'Input_63', 
    'curls_factor'                          : 'Input_43', 
    'curls_contrast'                        : 'Input_139', 
    # BRAID  
    'braid_frequency'                       : 'Input_65', 
    'braid_width'                           : 'Input_66', 
    'braid_depth'                           : 'Input_67', 
    'braid_taper'                           : 'Input_69', 
    'braid_phase'                           : 'Input_92', 
    'braid_strand_thickness'                : 'Input_68', 
    'braid_pinch'                           : 'Input_70', 
    'braid_bulge'                           : 'Input_71',
    'braid_tip'                             : 'Socket_83',
    'braid_tip_thickness'                   : 'Socket_84',
    'braid_tip_width'                       : 'Socket_110',
    'braid_tip_ornament'                    : 'Socket_111',
    'braid_strand_random'                   : 'Input_72', 
    'braid_strand_random_seed'              : 'Input_74', 
    'braid_strand_1_twist'                  : 'Input_89', 
    'braid_strand_1_rotate'                 : 'Socket_10', 
    'braid_strand_2_twist'                  : 'Socket_11', 
    'braid_strand_2_rotate'                 : 'Socket_13', 
    'braid_strand_3_twist'                  : 'Socket_12', 
    'braid_strand_3_rotate'                 : 'Socket_14', 
    # PROFILE
    'profile_type'                          : 'Input_93', 
    'profile_smooth'                        : 'Input_81', 
    'profile_preserve_corners'              : 'Input_83', 
    'profile_sub_strands'                   : 'Input_84', 
    'profile_ss_scale'                      : 'Input_85', 
    'profile_ss_seed'                       : 'Input_86', 
    'profile_islands_open'                  : 'Socket_39', 
    'profile_islands_bulge'                 : 'Socket_40', 
    'profile_islands_round'                 : 'Socket_41', 
    'profile_bend'                          : 'Socket_37', 
    'profile_thickness'                     : 'Socket_38', 
    'profile_custom'                        : 'Input_9', 
    # ORNAMENTS
    'ornaments_enable'                      : 'Input_130', 
    'ornaments_position'                    : 'Socket_17', 
    'ornaments_width'                       : 'Socket_18', 
    'ornaments_pinch'                       : 'Socket_19', 
    'ornaments_tightness'                   : 'Socket_20', 
    'ornaments_in_bump_gaps'                : 'Input_136', 
    'ornaments_disable_root'                : 'Input_137', 
    'ornaments_disable_tip'                 : 'Input_138', 
    'ornaments_type'                        : 'Input_123', 
    'ornaments_thickness'                   : 'Socket_23', 
    'ornaments_adjust_size'                 : 'Socket_21', 
    'ornaments_rotate'                      : 'Socket_22', 
    'ornaments_rotate_random'               : 'Socket_32', 
    'ornaments_adjust_range'                : 'Socket_78', 
    'ornaments_ribs'                        : 'Socket_24', 
    'ornaments_ribs_scale'                  : 'Socket_25', 
    'ornaments_ribs_twist'                  : 'Socket_26', 
    'ornaments_ribs_orientation'            : 'Socket_27', 
    'ornaments_coil'                        : 'Socket_28', 
    'ornaments_coil_radius'                 : 'Socket_29', 
    'ornaments_scrunch'                     : 'Socket_30', 
    'ornaments_scrunch_seed'                : 'Socket_31', 
    'ornaments_custom'                      : 'Input_119', 
    'ornaments_object'                      : 'Input_128', 
    'ornaments_collection'                  : 'Input_150', 
    'ornaments_individual_obj'              : 'Input_151', 
    'ornaments_obj_seed'                    : 'Input_152',
    'ornaments_deform'                      : 'Socket_108',
    'ornaments_deform_axis'                 : 'Socket_109', 
    # DYNAMICS
    'dynamics_enable'                       : 'Input_105', 
    'dynamics_stiffness'                    : 'Input_108', 
    'dynamics_elasticity'                   : 'Socket_35', 
    'dynamics_damping'                      : 'Input_109', 
    'dynamics_liveliness'                   : 'Socket_55', 
    'dynamics_factor'                       : 'Input_110', 
    'dynamics_contrast'                     : 'Socket_34', 
    'dynamics_gravity_strength'             : 'Input_107', 
    'dynamics_gravity_direction'            : 'Socket_56', 
    'dynamics_collisions_enable'            : 'Input_111', 
    'dynamics_collisions_object'            : 'Input_112', 
    'dynamics_collisions_offset'            : 'Input_114', 
    'dynamics_collisions_repel'             : 'Socket_68', 
    'dynamics_collisions_quality'           : 'Input_113', 
    'dynamics_sim_points'                   : 'Socket_54', 
    'dynamics_sim_smoothing'                : 'Socket_57', 
    'dynamics_sim_complex_curls'            : 'Socket_69',
    'dynamics_wind_generation_type'         : 'Socket_82',
    'dynamics_wind_force'                   : 'Socket_58', 
    'dynamics_wind_speed'                   : 'Socket_60', 
    'dynamics_wind_turbulence'              : 'Socket_59', 
    'dynamics_wind_turbulence_type'         : 'Socket_61', 
    'dynamics_wind_turbulence_orientation'  : 'Socket_62',
    'dynamics_wind_turbulence_scale'        : 'Socket_121',
    'dynamics_wind_direction'               : 'Socket_63', 
    'dynamics_wind_use_effector'            : 'Socket_64', 
    'dynamics_wind_effector_object'         : 'Socket_65', 
    'dynamics_wind_effector_type'           : 'Socket_66',
    'dynamics_random_per_obj'               : 'Socket_122',
    # MATERIALS
    'material_hair'                         : 'Input_6', 
    'material_ornament'                     : 'Input_129', 
    'material_uv_switch_order'              : 'Input_95', 
    'material_uv_extend'                    : 'Input_96', 
    'material_uv_pack'                      : 'Input_98', 
    'material_uv_margin'                    : 'Input_97', 
    'material_shade_color'                  : 'Socket_42', 
    'material_shade_noise_scale'            : 'Socket_43', 
    'material_shade_noise_contrast'         : 'Socket_44', 
    'material_shade_noise_seed'             : 'Socket_45', 
    'material_shade_noise_twist'            : 'Socket_76', 
    'material_shade_ss_blur'                : 'Input_144', 
    'material_shade_ss_balance'             : 'Input_146', 
    'material_shade_ss_contrast'            : 'Input_145', 
    'material_shade_ss_seed'                : 'Input_147', 
    'material_shade_random_seed'            : 'Input_149', 
    'material_shade_ends_tip'               : 'Input_156', 
    'material_shade_ends_tip_contrast'      : 'Input_157', 
    'material_shade_ends_root'              : 'Input_154', 
    'material_shade_ends_root_contrast'     : 'Input_155', 
    'material_shade_ends_noise'             : 'Input_168', 
    'material_shade_ends_noise_contrast'    : 'Socket_36', 
    'material_shade_anime_move'             : 'Socket_46', 
    'material_shade_anime_size'             : 'Socket_47', 
    'material_shade_anime_shift'            : 'Socket_53', 
    'material_shade_anime_brightness'       : 'Socket_48', 
    'material_shade_anime_detail'           : 'Socket_49', 
    'material_shade_anime_distortion'       : 'Socket_50', 
    'material_shade_anime_distortion_scale' : 'Socket_52', 
    'material_shade_anime_distortion_seed'  : 'Socket_51', 
    # SETTINGS
    'settings_pre_smooth'                   : 'Socket_33', 
    'settings_resolution_curve'             : 'Input_61', 
    'settings_resolution_profile'           : 'Input_88', 
    'settings_resolution_ornament'          : 'Socket_77', 
    'settings_resolution_auto_adjust'       : 'Socket_0', 
    'settings_resolution_taper'             : 'Socket_67', 
    'settings_shading_type'                 : 'Socket_15', 
    'settings_auto_smooth_angle'            : 'Socket_16', 
    'settings_subd_hair'                    : 'Input_142', 
    'settings_subd_geo'                     : 'Input_117', 
    'settings_flip_normals'                 : 'Input_13',
    # UTILITIES 
    'utils_armature_toggle_guide'           : 'Socket_74',
    'utils_armature_generate'               : 'Socket_81',
    'utils_armature_preview'                : 'Socket_70', 
    'utils_armature_preview_scale'          : 'Socket_71', 
    'utils_armature_bones'                  : 'Socket_72', 
    'utils_armature_taper'                  : 'Socket_73', 
    'utils_armature_use_curl'               : 'Socket_75',
    'utils_bbone_armature_handles'          : 'Socket_116',
    'utils_bbone_armature_segments'         : 'Socket_117',
    'utils_bbone_armature_handle_size'      : 'Socket_118',
    'utils_armature_type'                   : 'Socket_119',
    'utils_use_custom_hair_geo'             : 'Socket_114',
    'utils_custom_hair_object'              : 'Socket_115',
    'utils_custom_hair_object_axis'         : 'Socket_113',
    }


# The imputs for the path for the 'Global Values' ('name', 'group in the node tree', 'socket number')
SHP_GLOBAL_VALUES = (
    ("Settings Scale Factor",           "SHP_nt_global_settings_scale", 0),
    ("Hair Material",                   "SHP_nt_global_material_1",     2),
    ("Set Hair Material",               "SHP_nt_global_material_1",     1),
    ("Ornament Material",               "SHP_nt_global_material_2",     2),
    ("Set Ornament Material",           "SHP_nt_global_material_2",     1),
    ("Switch UV Order",                 "SHP_nt_global_uv_1",           2),
    ("Set Switch UV Order",             "SHP_nt_global_uv_1",           1),
    ("Extend UV",                       "SHP_nt_global_uv_1",           5),
    ("Set Extend UV",                   "SHP_nt_global_uv_1",           4),
    ("Pack UV Islands",                 "SHP_nt_global_uv_2",           8),
    ("Set Pack UV Islands",             "SHP_nt_global_uv_2",           7),
    ("Margin",                          "SHP_nt_global_uv_2",           11),
    ("Set Margin",                      "SHP_nt_global_uv_2",           10),
    ("Stiffness",                       "SHP_nt_global_dynamics_1",     2),
    ("Set Stiffness",                   "SHP_nt_global_dynamics_1",     1),
    ("Elasticity",                      "SHP_nt_global_dynamics_1",     5),
    ("Set Elasticity",                  "SHP_nt_global_dynamics_1",     4),
    ("Damping",                         "SHP_nt_global_dynamics_1",     8),
    ("Set Damping",                     "SHP_nt_global_dynamics_1",     7),
    ("Liveliness",                      "SHP_nt_global_dynamics_1",     11),
    ("Set Liveliness",                  "SHP_nt_global_dynamics_1",     10),
    ("Effect Factor",                   "SHP_nt_global_dynamics_1",     14),
    ("Set Effect Factor",               "SHP_nt_global_dynamics_1",     13),
    ("Contrast",                        "SHP_nt_global_dynamics_1",     17),
    ("Set Contrast",                    "SHP_nt_global_dynamics_1",     16),
    ("Gravity Strength",                "SHP_nt_global_dynamics_1",     20),
    ("Set Gravity Strength",            "SHP_nt_global_dynamics_1",     19),
    ("Gravity Direction",               "SHP_nt_global_dynamics_1",     23),
    ("Set Gravity Direction",           "SHP_nt_global_dynamics_1",     22),
    ("Collider Object",                 "SHP_nt_global_dynamics_1",     26),
    ("Set Collider Object",             "SHP_nt_global_dynamics_1",     25),
    ("Offset Distance",                 "SHP_nt_global_dynamics_1",     29),
    ("Set Offset Distance",             "SHP_nt_global_dynamics_1",     28),
    ("Repel Force",                     "SHP_nt_global_dynamics_1",     32),
    ("Set Repel Force",                 "SHP_nt_global_dynamics_1",     31),
    ("Quality Steps",                   "SHP_nt_global_dynamics_1",     35),
    ("Set Quality Steps",               "SHP_nt_global_dynamics_1",     34),
    ("Wind Force",                      "SHP_nt_global_dynamics_1",     38),
    ("Set Wind Force",                  "SHP_nt_global_dynamics_1",     37),
    ("Wind Speed",                      "SHP_nt_global_dynamics_1",     41),
    ("Set Wind Speed",                  "SHP_nt_global_dynamics_1",     40),
    ("Turbulence",                      "SHP_nt_global_dynamics_1",     44),
    ("Set Turbulence",                  "SHP_nt_global_dynamics_1",     43),
    ("Complex / Simple",                "SHP_nt_global_dynamics_1",     47),
    ("Set Complex / Simple",            "SHP_nt_global_dynamics_1",     46),
    ("Wave Orientation",                "SHP_nt_global_dynamics_1",     50),
    ("Set Wave Orientation",            "SHP_nt_global_dynamics_1",     49),
    ("Wind Direction",                  "SHP_nt_global_dynamics_1",     53),
    ("Set Wind Direction",              "SHP_nt_global_dynamics_1",     52),
    ("Use Effector",                    "SHP_nt_global_dynamics_1",     56),
    ("Set Use Effector",                "SHP_nt_global_dynamics_1",     55),
    ("Effector Object",                 "SHP_nt_global_dynamics_1",     59),
    ("Set Effector Object",             "SHP_nt_global_dynamics_1",     58),
    ("Attract / Repel",                 "SHP_nt_global_dynamics_1",     62),
    ("Set Attract / Repel",             "SHP_nt_global_dynamics_1",     61),
    ("Simulation Points",               "SHP_nt_global_dynamics_1",     65),
    ("Set Simulation Points",           "SHP_nt_global_dynamics_1",     64),
    ("Post-sim Smoothing",              "SHP_nt_global_dynamics_1",     68),
    ("Set Post-sim Smoothing",          "SHP_nt_global_dynamics_1",     67),
    ("Complex Curls Simulation",        "SHP_nt_global_dynamics_1",     71),
    ("Set Complex Curls Simulation",    "SHP_nt_global_dynamics_1",     70),
    ("Wave Scale",                      "SHP_nt_global_dynamics_1",     74),
    ("Set Wave Scale",                  "SHP_nt_global_dynamics_1",     73),
)


# The names of the node groups, used for the auto-update feature
SHP_NODE_GROUPS = (
    # the old ones, before v3.14 
    "Adder (GEO)",
    "Armature Guide",
    "Box Profile",
    "Braid",
    "Braid Deform",
    "Bumps",
    "Close Tips",
    "Combined UV Map",
    "Contrast",
    "Crescent Profile",
    "Curl Hair Curve",
    "Curve Attributes",
    "Curve Noise 2",
    "Curve Range",
    "Curve to Mesh with UV",
    "Custom Ornament",
    "Easing (Bezier)",
    "Flatten",
    "Flip Control",
    "Global Hair Dynamics Settings",
    "Global Material Settings",
    "Global Position",
    "Global UV Settings",
    "Hair Band",
    "Hair Dynamics",
    "Index Selection",
    "Inflate Geometry",
    "Instance on Bumps Gaps",
    "Islands Profile",
    "Line Profile",
    "Multiplier (GEO)",
    "Normalize Attribute",
    "Normalize Attribute Value",
    "Object Trasforms",
    "Ornament Curve",
    "Ornaments in Bump Gaps",
    "Ornaments on Curve",
    "Pick Boolean",
    "Pick Float",
    "Pick Geometry",
    "Pick String",
    "Pick Vector",
    "Pinch Hair Curve",
    "Positive Integer",
    "Procedural Hair Profile",
    "Read Edge Angle",
    "Remove Splines",
    "Ring Ornament",
    "Ring/Coil",
    "Robo Profile",
    "Rotate and Twist",
    "Scale Factor Input",
    "Scrunchie",
    "Scrunchie Ornament",
    "Setting Scale Factor",
    "Shape",
    "Smooth Geometry",
    "Solidify Mesh",
    "Strand Shade",
    "Surface Bumps",
    "Taper Curve Points",
    "Triangle Proflie",
    "X-Mirror Geo",
    "Stylized Hair PRO",
    # the new node group names, after v3.14
    ".SHP_adder",
    ".SHP_armature_guide",
    ".SHP_bezier_easing",
    ".SHP_braid",
    ".SHP_braid_deform",
    ".SHP_braid_select_strands"
    ".SHP_bumps",
    ".SHP_close_tips",
    ".SHP_combined_uv_map",
    ".SHP_contrast",
    ".SHP_contrast_shader",
    ".SHP_curl_curve",
    ".SHP_curve_attributes",
    ".SHP_curve_noise",
    ".SHP_curve_range",
    ".SHP_curve_to_mesh_uv",
    ".SHP_custom_ornament",
    ".SHP_dynamics",
    ".SHP_flatten",
    ".SHP_flip_control",
    ".SHP_global_dynamics",
    ".SHP_global_material",
    ".SHP_global_uv",
    ".SHP_index_selection",
    ".SHP_inflate_geometry",
    ".SHP_instance_on_bump_gaps",
    ".SHP_mirror_geo",
    ".SHP_multiplier",
    ".SHP_normalize_attribute",
    ".SHP_normalize_attribute_value",
    ".SHP_object_transforms",
    ".SHP_ornament_band",
    ".SHP_ornament_curve",
    ".SHP_ornament_ring",
    ".SHP_ornament_scrunchie",
    ".SHP_ornaments_in_bump_gaps",
    ".SHP_ornaments_on_curve",
    ".SHP_pick_boolean",
    ".SHP_pick_float",
    ".SHP_pick_geometry",
    ".SHP_pick_string",
    ".SHP_pick_vector",
    ".SHP_pick_color",
    ".SHP_pinch_curve",
    ".SHP_position_global",
    ".SHP_positive_integer",
    ".SHP_profile_box",
    ".SHP_profile_crescent",
    ".SHP_profile_curves",
    ".SHP_profile_islands",
    ".SHP_profile_line",
    ".SHP_profile_robo",
    ".SHP_profile_triangle",
    ".SHP_read_edge_angle",
    ".SHP_remove_splines",
    ".SHP_ring_coil",
    ".SHP_rotate_twist",
    ".SHP_scale_factor_input",
    ".SHP_scrunchie",
    ".SHP_settings_scale_factor",
    ".SHP_shape",
    ".SHP_smooth_geometry",
    ".SHP_solidify_mesh",
    ".SHP_strands_shade",
    ".SHP_surface_bumps",
    ".SHP_taper_curve_points",
    ".SHP_curve_deform",
    ".SHP_bbone_armature_guide",
    ".SHP_bbone_curve",
    ".SHP_braid_select_strands",
    ".SHP_bumps",
    ".SHP_curve_root",
    ".SHP_curve_segment",
    ".SHP_restore_curve_length",
    ".SHP_set_bezier_segment_shape",
)
